image:
    file: .gitpod.Dockerfile

additionalRepositories:
    - url: https://github.com/Arges42/heltour
      # checkoutLocation is relative to /workspaces
      checkoutLocation: 4545compose/heltour